In [93]:
import pandas as pd
import numpy as np

url = "https://en.wikipedia.org/wiki/List_of_countries_by_GDP_%28nominal%29"

## 1-) pandas ile web sayfası tablolarını çıkar. ve ilgili 3. tabloyu al

In [94]:
df = pd.read_html(url, storage_options={"User-Agent": "Mozilla/5.0"})[2]
df

,Country/Territory,IMF (2026)[1],World Bank (2025)[6],United Nations (2024)[7]
0,World,126295331,118350166,111565144
1,United States,32383920,30769700,29298000
2,China[n 1],20851593,19498039,18743802
3,Germany,5452858,5050923,4659929
4,Japan,4379253,4435163,4026211
...,...,...,...,...
217,Palau,377,345,310
218,Marshall Islands,342,308,281
219,Nauru,196,176,187
220,Montserrat,—N/a,—N/a,81
221,Tuvalu,65,57,56

## Sütun başlıklarını sütun numaralarıyla değiştirin

In [95]:
df.columns = range(len(df.columns))
df.columns = [0, 1, 2, 3]
df

                    0          1          2          3
0               World  126295331  118350166  111565144
1       United States   32383920   30769700   29298000
2          China[n 1]   20851593   19498039   18743802
3             Germany    5452858    5050923    4659929
4               Japan    4379253    4435163    4026211
..                ...        ...        ...        ...
217             Palau        377        345        310
218  Marshall Islands        342        308        281
219             Nauru        196        176        187
220        Montserrat       —N/a       —N/a         81
221            Tuvalu         65         57         56

[222 rows x 4 columns]

## 0 ve 2. indeksli sütunları saklayın (ülke adı ve IMF tarafından belirtilen GSYİH değeri)

In [96]:
df = df.drop(columns=[1,3])
df

                    0          2
0               World  118350166
1       United States   30769700
2          China[n 1]   19498039
3             Germany    5050923
4               Japan    4435163
..                ...        ...
217             Palau        345
218  Marshall Islands        308
219             Nauru        176
220        Montserrat       —N/a
221            Tuvalu         57

[222 rows x 2 columns]

## Dünyanın en büyük 10 ekonomisini temsil eden, 1 ila 10. indeks aralığındaki satırları saklayın.

In [97]:
df[1:11]

                 0         2
1    United States  30769700
2       China[n 1]  19498039
3          Germany   5050923
4            Japan   4435163
5   United Kingdom   4002588
6            India   3956067
7           France   3366316
8            Italy   2551557
9           Russia   2561310
10          Brazil   2279920

## Sütun adlarını "Country" ve "GDP (Million USD)" olarak atayın

In [98]:
# df2 = df.copy()
# df2.columns = ["Country", "GDP (Million USD)"]
# df2

df.columns = ["Country", "GDP(Million USD)"]
df.head()

         Country GDP(Million USD)
0          World        118350166
1  United States         30769700
2     China[n 1]         19498039
3        Germany          5050923
4          Japan          4435163

### DataFrame'in GDP sütununu, Milyon USD cinsinden olan değeri Milyar USD'ye dönüştürerek değiştirin. Değeri virgülden sonra iki basamağa yuvarlamak için NumPy kütüphanesinin round() metodunu kullanın. DataFrame'in başlığını "GDP (Billion USD)" olarak değiştirin.

In [ ]:
## 'GDP (Million USD)' sütununun veri türünü tam sayıya (integer) dönüştürün.
#  astype() yöntemini kullanın.

df2 = df.copy()
df2['GDP(Million USD)'] = pd.to_numeric(df2['GDP(Million USD)'], errors='coerce').fillna(0).astype(int)

## Milyon USD cinsinden GSYİH değerini Milyar USD'ye dönüştürün.
df2["GDP(Million USD)"] = pd.to_numeric(df2["GDP(Million USD)"], errors="coerce").fillna(0)/1000
df2

# Değeri virgülden sonra iki basamağa yuvarlamak için numpy.round() yöntemini kullanın.

df3 = df2.copy()
df3["GDP(Million USD)"] = np.round(df3[["GDP(Million USD)"]], 2)
df3

# Sütun başlığını 'GDP (Million USD)' yerine 'GDP (Billion USD)' olarak değiştirin.

df3 = df3.rename(columns={"GDP(Million USD)": "GDP(BİLLİON USD)"})
df3

              Country  GDP(BİLLİON USD)
0               World         118350.17
1       United States          30769.70
2          China[n 1]          19498.04
3             Germany           5050.92
4               Japan           4435.16
..                ...               ...
217             Palau              0.34
218  Marshall Islands              0.31
219             Nauru              0.18
220        Montserrat              0.00
221            Tuvalu              0.06

[222 rows x 2 columns]

In [137]:
# DataFrame'i "Largest_economies.csv" adlı CSV dosyasına yükleyin

df3.to_csv("Largest_economies.csv")